apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-hello-reconciler
  namespace: flux-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-hello-flux-reconciler
  namespace: platform-demo
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-hello-flux-reconciler
  namespace: platform-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-hello-flux-reconciler
subjects:
  - kind: ServiceAccount
    name: platform-hello-reconciler
    namespace: flux-system
